### ISSUE TITLE
Anti-Cheat

### ISSUE THREAD

**Issue by pietrosprudente** [lstwo/lstwoMODS#2]
3 Second Cooldown for some buttons like teleport all players being used to cheat in-game and disable the character manager and ragdoll manager for other players in some arcade games, hosts can abuse these things with lstwoMods,

**Comment by lstwo** [comment]
I honestly don't know if I'd want to add an anti-cheat as the whole point of the mod is to give users freedom, but if something can be abused very maliciously i might patch that.
